spring:
  profiles:
    include:
      - database
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


token:
  expiration_time : 1000L * 60 * 30 # 하루
  secret: user_token


# 우아한 형제들 기술블로그
woowahan:
  blog:
    url: https://techblog.woowahan.com