spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:devdb
    driver-class-name: org.h2.Driver
    username: dlog
    password: 1234

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  cache:
    type: redis
#  redis:
#    host: 127.0.0.1
#    port: 6379

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}

  mail:
    host: smtp.gmail.com
    port: 587
    username: schulnoh@gmail.com
    password: ucgfiptbadbbuwbv
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
    default-encoding: UTF-8

security:
  jwt:
    token:
      secret-key: U0NOT0hfREFJTFlfREVWX0xPR19QUk9KRUNU
      access:
        expire-length: 3600000 #1시간
        refresh:
          expire-length: 1210000000 #14일

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://scnohdb.cscks1c1hr2u.us-west-1.rds.amazonaws.com/DEV_DB?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: scnoh
    password: scnoh0760!
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  batch:
    jdbc:
      initialize-schema: never
    job:
      names: ${job.name:NONE}
  mail:
    host: smtp.gmail.com
    port: 587
    username: schulnoh@gmail.com
    password: sjtmppuixgireous
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
    default-encoding: UTF-8
token:
  expiration_time : 1000L * 60 * 30 # 하루
  secret: user_token

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: /app/data/log/dlog.log
  level:
    com.news.dev: debug

---

daily:
  woowahan: # 우아한 형제들 기술블로그
    blog:
      url: https://techblog.woowahan.com
  naver: # 네이버 IT 뉴스
    it-news:
      url: https://news.naver.com/main/list.naver?mode=LS2D&mid=shm&sid1=105&sid2=226
  kakao: # 카카오 기술블로그
    blog:
      url: https://tech.kakao.com/blog/