spring:
  profiles:
    include: database, mail, file

server:
  servlet:
    context-path: /dailyb

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    groups:
      enabled: false


daily:
  woowahan: # 우아한 형제들 기술블로그
    blog:
      url: https://techblog.woowahan.com
  naver: # 네이버 IT 뉴스
    it-news:
      url: https://news.naver.com/main/list.naver?mode=LS2D&mid=shm&sid1=105&sid2=226
  kakao: # 카카오 기술블로그
    blog:
      url: https://tech.kakao.com/blog/

jasypt:
  encryptor:
    property:
      prefix: ENC(
      suffix: )
    bean: jasyptStringEncryptor
  password : daily_dev_encrypt

---

spring:
  config:
    activate:
      on-profile: local

  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.name:NONE}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 78a76271b80584ab4494
            client-secret: a8551c28f4da52320acbdb1de659b3d7c1b0a89e

security:
  jwt:
    token:
      secret-key: U0NOT0hfREFJTFlfREVWX0xPR19QUk9KRUNU
      access:
        expire-length: 3600000 #1시간
      refresh:
        expire-length: 1210000000 #14일

logging:
  level:
    com.daily: debug

---

spring:
  config:
    activate:
      on-profile: prod

  batch:
    jdbc:
      initialize-schema: never
    job:
      names: ${job.name:NONE}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 78a76271b80584ab4494
            client-secret: a8551c28f4da52320acbdb1de659b3d7c1b0a89e

security:
  jwt:
    token:
      secret-key: U0NOT0hfREFJTFlfREVWX0xPR19QUk9KRUNU
      access:
        expire-length: 3600000 #1시간
        refresh:
          expire-length: 1210000000 #14일

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: /patch/log
  level:
    com.daily: info


