spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://scnohdb.cscks1c1hr2u.us-west-1.rds.amazonaws.com/DEV_DB?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: scnoh
    password: scnoh0760!
