# Email Template Settings
spring:

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(TjSgrVLEMfKqzyrLJUxL+PBt6Rch54uNiIAuXhvget4=)
    password: ENC(0VAHzOlZmGAfP/40qmzJIN9ckyj6kxSaNS+Vb07J7po=)
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
    default-encoding: UTF-8
