# Email Template Settings
spring:

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(EP2WJhvqF+Kk8GTohpsZdJSOmqvC1O3fd1BAyltcmqQ=)
    password: ENC(EMvfDWtyh4khmjS92HKICs3YZicbmO68wiXx3NgHTu4=)
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
    default-encoding: UTF-8
