# Email Template Settings
spring:

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    check-template-location: true
    cache: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(zSNdjWWogYsWbZcjMqV1Puinp6aYG80Y6Duc9lQ/rReK0KMDKFlZDcbHPXQZEGpy7ku78cB9vjFS+cqEnHVBeQ==)
    password: ENC(aqxOofn4VjOv0HF16R0clKWf6z3bgmm7dAE7sTZFmLhnZIprLd3MF0tz5M7DpklG/EnDD7mRt+3SXl6qLyfkrw==)
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          timeout: 5000
          starttls.enable: true
    default-encoding: UTF-8
