spring:
  profiles:
    include:
      - database
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  batch:
    jdbc:
      initialize-schema: always


token:
  expiration_time : 1000L * 60 * 30 # 하루
  secret: user_token


# 우아한 형제들 기술블로그
woowahan:
  blog:
    url: https://techblog.woowahan.com